export const ADDTOCARTITEM_REQUEST = 'ADDTOCARTITEM_REQUEST';
export const ADDTOCARTITEM_RESPONSE = 'ADDTOCARTITEM_RESPONSE';
export const ADDTOCARTITEM_FAILD = 'ADDTOCARTITEM_FAILD';

export const LOADCARTITEMS_REQUEST = 'LOADCARTITEMS_REQUEST';
export const LOADCARTITEMS_RESPONSE = 'LOADCARTITEMS_RESPONSE';
export const LOADCARTITEMS_FAILD = 'LOADCARTITEMS_FAILD';

export const UPDATEQUANTITY_REQUEST = 'UPDATEQUANTITY_REQUEST';
export const UPDATEQUANTITY_RESPONSE = 'UPDATEQUANTITY_RESPONSE';
export const UPDATEQUANTITY_FAILD = 'UPDATEQUANTITY_FAILD';

export const REMOVECARTITEMS_REQUEST = 'REMOVECARTITEMS_REQUEST';
export const REMOVECARTITEMS_RESPONSE = 'REMOVECARTITEMS_RESPONSE';
export const REMOVECARTITEMS_FAILD = 'REMOVECARTITEMS_FAILD';


export const ADDTOCARTITEMS="ADDTOCARTITEMS"
export const REMOVECARTITEMS = 'REMOVECARTITEMS';
export const LOAD_CARTITEMS = 'LOAD_CARTITEMS';
export const ADDCARTITEM_REQUEST = 'ADDCARTITEM_REQUEST';

