export const ORDER_REQUEST="ORDER_REQUEST"
export const ORDER_RESPONSE="ORDER_RESPONSE"
export const ORDER_FAILED="ORDER_FAILED"

export const LOAD_ORDER_REQUEST="LOAD_ORDER_REQUEST"
export const LOAD_ORDER_RESPONSE="LOAD_ORDER_RESPONSE"
export const LOAD_ORDER_FAILED="LOAD_ORDER_FAILED"

export const ORDERDETAILS_REQUEST="ORDERDETAILS_REQUEST"
export const ORDERDETAILS_RESPONSE="ORDERDETAILS_RESPONSE"
export const ORDERDETAILS_FAILED="ORDERDETAILS_FAILED"


export const CLEAR_ERRORS="CLEAR_ERRORS"