export const ALL_PRODUCT_REQUEST="ALL_PRODUCT_REQUEST"
export const ALL_PRODUCT_SUCCESS="ALL_PRODUCT_SUCCESS"
export const ALL_PRODUCT_FAIL="ALL_PRODUCT_FAIL"

export const PRODUCT_DETAILS_REQUEST="PRODUCT_DETAILS_REQUEST"
export const PRODUCT_DETAILS_SUCCESS="PRODUCT_DETAILS_SUCCESS"
export const PRODUCT_DETAILS_FAIL=" PRODUCT_DETAILS_FAIL"


export const REVIEW_CREATE_REQUEST="REVIEW_CREATE_REQUEST"
export const REVIEW_CREATE_SUCCESS="REVIEW_CREATE_SUCCESS"
export const REVIEW_CREATE_FAIL=" REVIEW_CREATE_FAIL"
export const REVIEW_CREATE_RESET=" REVIEW_CREATE_RESET"

export const ADMIN_GETPRODUCT_REQUEST="ADMIN_GETPRODUCT_REQUEST"
export const ADMIN_GETPRODUCT_SUCCESS="ADMIN_GETPRODUCT_SUCCESS"
export const ADMIN_GETPRODUCT_FAIL=" ADMIN_GETPRODUCT_FAIL"

export const ADMIN_CREATEPRODUCT_REQUEST="ADMIN_CREATEPRODUCT_REQUEST"
export const ADMIN_CREATEPRODUCT_SUCCESS="ADMIN_CREATEPRODUCT_SUCCESS"
export const ADMIN_CREATEPRODUCT_FAIL=" ADMIN_CREATEPRODUCT_FAIL"

export const ADMIN_updatePRODUCT_REQUEST="ADMIN_updatePRODUCT_REQUEST"
export const ADMIN_updatePRODUCT_SUCCESS="ADMIN_updatePRODUCT_SUCCESS"
export const ADMIN_updatePRODUCT_FAIL=" ADMIN_updatePRODUCT_FAIL"

export const PRODUCTDELETE_REQUEST="PRODUCTDELETE_REQUEST"
export const PRODUCTDELETE_SUCCESS="PRODUCTDELETE_SUCCESS"
export const PRODUCTDELETE_FAIL=" PRODUCTDELETE_FAIL"



export const Clearproduct="Clearproduct"
export const CLEAR_ERROR="CLEAR_ERROR"