export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const LOADUSER_REQUEST = 'LOADUSER_REQUEST';
export const LOADUSER_SUCCESS = 'LOADUSER__SUCCESS';
export const LOADUSER_FAILED = 'LOADUSER_FAILED';

export const SINUP_REQUEST = 'SINUP_REQUEST';
export const SINUP_SUCCESS = 'SINUP_SUCCESS';
export const SINUP_FAILED = 'SINUP_FAILED';


export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';

export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILED = 'UPDATE_PROFILE_FAILED';
export const UPDATE_PROFILE_RESET = 'UPDATE_PROFILE_RESET';

export const FORGOTPASSWORD_mail_REQUEST = 'FORGOTPASSWORD_mail_REQUEST';
export const FORGOTPASSWORD_mail_SUCCESS = 'FORGOTPASSWORD_mail_SUCCESS';
export const FORGOTPASSWORD_mail_FAILED = 'FORGOTPASSWORD_mail_FAILED';
export const FORGOTPASSWORD_mail_RESET = 'FORGOTPASSWORD_mail_RESET';

export const ADMIN_ALLUSERS_REQUEST = 'ADMIN_ALLUSERS_REQUEST';
export const ADMIN_ALLUSERS_SUCCESS = 'ADMIN_ALLUSERS_SUCCESS';
export const ADMIN_ALLUSERS_FAILED = 'ADMIN_ALLUSERS_FAILED';




export const PASSWORDCHANGE_REQUEST = 'PASSWORDCHANGGE_REQUEST';
export const PASSWORDCHANGE_SUCCESS = 'PASSWORDCHANGGE_SUCCESS';
export const PASSWORDCHANGE_FAILED = 'PASSWORDCHANGGE_FAILED';